Trigger a change event when original input value is updated.
jcubic/tagger pull request #36
Opened 2023-03-14 11:58 UTC by sheabunge

When tagger updates the original input field with the list of tags, there's currently no easy way to subscribe to those changes and trigger further actions, whether you're using vanilla JavaScript, React, or something else.

This pull requests has tagger trigger the `change` event hook when it writes to the input field's value, allowing for further integrations.

2023-03-14 14:42 UTC, jcubic commented
Sorry, but I don't like to use the native change event for this purpose there is issue #18 this is what I would like to have.

2023-03-14 14:44 UTC, jcubic commented
I'm thinking right now if this is not a better approach, to have a change event.

2023-03-14 14:45 UTC, jcubic requested changes

2023-03-14 14:45 UTC, jcubic commented on tagger.js
> +          this._input.dispatchEvent(new Event('change', { bubbles: true }))
Missing semicolon

2023-03-14 14:45 UTC, jcubic commented on tagger.js
> +                        self._update_input()
Missing semicolon

2023-03-14 14:45 UTC, jcubic commented on tagger.js
> +            this._update_input()
Missing semicolon

2023-03-14 14:45 UTC, jcubic commented on tagger.js
> +            this._update_input()
Missing semicolon

2023-03-14 15:57 UTC, sheabunge commented
#18 does sound good. Would these be exposed as callback options?

2023-03-14 16:52 UTC, jcubic commented
Yes, they suppose to be options, but I think that change event is also a good idea.

2023-07-26 04:31 UTC, lucasnetau commented
Are the missing semicolons the only things preventing this PR from being merged? I've been running something like this patch for a while but it would be nice to see it merged upstream. Having the change event allows us to synchronise the state of the tagger instance with a server without needing to do polling via setTimeout or waiting for the user to click a save button.

2023-07-26 07:40 UTC, jcubic commented
I think that I will just close this in favor of #18.

2023-07-28 13:34 UTC, closed without merging

2023-07-28 13:35 UTC, jcubic commented
The the continuation of the PR is in https://github.com/jcubic/tagger/pull/43